#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iPortaliAndroid.Resource", IsApplication=true)]

namespace iPortaliAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int accent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int splash_background = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int window_background = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo2858 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash_screen = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int autoCompleteTextView1 = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int btnFindStore = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int btnLatoOvest = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int btnPianoTerra = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int btnPrimoPiano = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int webView1 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int frmFindStore = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int frmLatoOvest = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int frmPianoTerra = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int frmPrimoPiano = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int ApplicationName = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int FindStore = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int MapOvest = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int MapPTerra = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MapPrimoPiano = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyTheme_Base = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MyTheme_Splash = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
